version: '3'
services:

#  redis:
#    image: redis:3.2.11
#    volumes:
#      - session-data:/data
#    networks:
#      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
      - index-data:/usr/share/elasticsearch/data
    networks:
      - backend
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  nats:
    image: nats:1.0.4
    networks:
      - backend

  crawl-service:
    image: node:6.11.4
    volumes:
      - crawl-data:/var/whatsclose-data
    networks:
      - backend
    depends_on:
      - nats

  band-service:
    image: node:6.11.4
    volumes:
      - band-data:/var/whatsclose-data
    networks:
      - backend
    depends_on:
      - nats

  geocode-service:
    image: node:6.11.4
    volumes:
      - geolocation-data:/var/whatsclose-data
    networks:
      - backend
    depends_on:
      - nats

  index-service:
    image: node:6.11.4
    networks:
      - backend
    depends_on:
      - elasticsearch
      - nats

networks:
  frontend:
  backend:

volumes:
#  session-data:
  index-data:
  crawl-data:
  geolocation-data:
  band-data:

