version: '3'
services:

#  redis:
#    image: redis:3.2.11
#    networks:
#      - backend

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
#    networks:
#      - backend

  nats:
    image: nats:1.0.4
    networks:
      - backend

  crawl-service:
    build:
      context: ${CRAWL_SOURCES}
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - nats

  band-service:
    build:
      context: ${BAND_SOURCES}
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - nats
#
#  geocode-service:
#    image: node:6.11.4
#    networks:
#      - backend
#    depends_on:
#      - nats
#
#  index-service:
#    image: node:6.11.4
#    networks:
#      - backend
#    depends_on:
#      - elasticsearch
#      - nats

networks:
  frontend:
  backend:

volumes:
  #session-data:
  #index-data:
  crawl-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CRAWL_DATA}
  band-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${BAND_DATA}
  #geolocation-data:
  #band-data:

